# Chaining this file to the main docker-compose file adds
# a default processing node instance. This is best for users
# who are just getting started with WebODM.

version: '2.1'
services:
  webapp:
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh --create-default-pnode\""
    depends_on:
      - node-odm
  node-odm:
    image: opendronemap/nodeodm
    command: --cleanup_tasks_after 60
    restart: on-failure:10
    oom_score_adj: 500
