# This configuration does not include a processing node
# Which makes for faster setup times
version: '2.1'
networks:
  web:
    external: true
volumes:
  dbdata:
  appmedia:
  appannotations:
services:
  db:
    image: opendronemap/webodm_db
    container_name: db
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: on-failure:10
    oom_score_adj: -100
  webapp:
    image: opendronemap/webodm_webapp
    container_name: webapp
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\""
    volumes:
      - ${WO_MEDIA_DIR}:/webodm/app/media
      - ${WO_ANNOTATIONS_DIR}:/webodm/app/annotations
    expose:
      - "8000"
    depends_on:
      - db
      - broker
      - worker
    environment:
      - WO_PORT
      - WO_HOST
      - WO_DEBUG
      - WO_BROKER
    restart: on-failure:10
    oom_score_adj: 0
    labels:
      - traefik.backend=webodm_webapp
      - traefik.frontend.rule=Host:localhost
      - traefik.docker.network=web
      - traefik.port=8000
      - traefik.enable=true
    networks:
      - web
      - default
  broker:
    image: redis
    container_name: broker
    restart: on-failure:10
    oom_score_adj: -500
  worker:
    image: opendronemap/webodm_webapp
    container_name: worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - ${WO_MEDIA_DIR}:/webodm/app/media
      - ${WO_ANNOTATIONS_DIR}:/webodm/app/annotations
    depends_on:
      - db
      - broker
    environment:
      - WO_BROKER
      - WO_DEBUG
    restart: on-failure:10
    oom_score_adj: 250
    networks:
      - web
      - default
