# Generated by Django 2.1.7 on 2019-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_plugin'),
    ]

    def migrate_from_import_url_to_import_album(apps, schema_editor):
        Task = apps.get_model('app', 'Task')

        for t in Task.objects.all():
            print("Updating {}".format(t))

            if 'category' in t.import_url:
                paths = t.import_url.split('/')
                album_id = paths[paths.index('category') + 1] 
                t.import_album = album_id
                t.import_url = ''
                t.save()

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT'), (6, 'IMPORT_IMAGES')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='import_album',
            field=models.IntegerField(default=-1, help_text="The id of the piwigo album where the images where imported from (null if they weren't imported from piwigo)")
        ),
        migrations.RunPython(migrate_from_import_url_to_import_album),
    ]
