# Generated by Django 2.1.7 on 2019-06-25 02:10

from django.db import migrations, models
from app.plugins import GlobalDataStore


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190625_0210'),
    ]

    def migrate_from_import_album_to_plugin(apps, schema_editor):
        Task = apps.get_model('app', 'Task')

        data_store = GlobalDataStore("cloudimport")

        for t in Task.objects.all():
            print("Updating {}".format(t))

            if t.import_album is not None and t.import_album > 0:
                album_url = "http://imagenes.bosques.dc.uba.ar/index.php?/category/" + str(t.import_album)
                combined_id = "{}_{}".format(t.project.id, t.id)
                data_store.set_string(combined_id, album_url)

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pending_action',
            field=models.IntegerField(blank=True, choices=[(1, 'CANCEL'), (2, 'REMOVE'), (3, 'RESTART'), (4, 'RESIZE'), (5, 'IMPORT')], db_index=True, help_text='A requested action to be performed on the task. The selected action will be performed by the worker at the next iteration.', null=True),
        ),
        migrations.RunPython(migrate_from_import_album_to_plugin),
        migrations.RemoveField(
            model_name='task',
            name='import_album'
        ),
    ]
